
Error in attempt 0:
Traceback (most recent call last):
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/bin/manim", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/manim/cli/render/commands.py", line 116, in render
    for SceneClass in scene_classes_from_file(file):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/manim/utils/module_ops.py", line 131, in scene_classes_from_file
    module = get_module(file_path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/manim/utils/module_ops.py", line 54, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/abderazzakoumad/Desktop/archive_manim/output/pythagorean_theorem_deepseek/pythagorean_theorem/scene1/code/pythagorean_theorem_scene1_v1.py", line 4, in <module>
    from manim_voiceover.services.gtts import gTTSService
ImportError: cannot import name 'gTTSService' from 'manim_voiceover.services.gtts' (/Users/abderazzakoumad/.pyenv/versions/3.11.8/lib/python3.11/site-packages/manim_voiceover/services/gtts.py)


Error in attempt 0:
[Errno 2] No such file or directory: 'manim'

Error in attempt 0:
/Users/snouae/goinfre/pip-cache/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
/bin/sh: sox: command not found
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.
    
╭────────────────────────── Traceback (most recent call last) ───────────────────────────╮
│ /Users/snouae/goinfre/pip-cache/manim/cli/render/commands.py:119 in render             │
│                                                                                        │
│   116 │   │   for SceneClass in scene_classes_from_file(file):                         │
│   117 │   │   │   try:                                                                 │
│   118 │   │   │   │   with tempconfig({}):                                             │
│ ❱ 119 │   │   │   │   │   scene = SceneClass()                                         │
│   120 │   │   │   │   │   scene.render()                                               │
│   121 │   │   │   except Exception:                                                    │
│   122 │   │   │   │   error_console.print_exception()                                  │
│                                                                                        │
│ /Users/snouae/goinfre/pip-cache/manim/scene/scene.py:147 in __init__                   │
│                                                                                        │
│    144 │   │   │   )                                                                   │
│    145 │   │   else:                                                                   │
│    146 │   │   │   self.renderer = renderer                                            │
│ ❱  147 │   │   self.renderer.init_scene(self)                                          │
│    148 │   │                                                                           │
│    149 │   │   self.mobjects = []                                                      │
│    150 │   │   # TODO, remove need for foreground mobjects                             │
│                                                                                        │
│ /Users/snouae/goinfre/pip-cache/manim/renderer/cairo_renderer.py:54 in init_scene      │
│                                                                                        │
│    51 │   │   self.static_image = None                                                 │
│    52 │                                                                                │
│    53 │   def init_scene(self, scene):                                                 │
│ ❱  54 │   │   self.file_writer: Any = self._file_writer_class(                         │
│    55 │   │   │   self,                                                                │
│    56 │   │   │   scene.__class__.__name__,                                            │
│    57 │   │   )                                                                        │
│                                                                                        │
│ /Users/snouae/goinfre/pip-cache/manim/scene/scene_file_writer.py:88 in __init__        │
│                                                                                        │
│    85 │   │   )                                                                        │
│    86 │   │   # fail fast if ffmpeg is not found                                       │
│    87 │   │   if not ensure_executable(Path(config.ffmpeg_executable)):                │
│ ❱  88 │   │   │   raise RuntimeError(                                                  │
│    89 │   │   │   │   "Manim could not find ffmpeg, which is required for generating v │
│    90 │   │   │   │   "For installing ffmpeg please consult https://docs.manim.communi │
│    91 │   │   │   │   "Make sure to either add ffmpeg to the PATH environment variable │
╰────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Manim could not find ffmpeg, which is required for generating video output.
For installing ffmpeg please consult 
https://docs.manim.community/en/stable/installation.html
Make sure to either add ffmpeg to the PATH environment variable
or set path to the ffmpeg executable under the ffmpeg header in Manim's configuration.

